apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "moscow-time.fullname" . }}-post-install"
  labels:
    {{- include "moscow-time.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "moscow-time.fullname" . }}-post-install"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Running smoke test..."
              sleep 5
              echo "Smoke test passed!"
