replicaCount: 1

image:
  repository: enot0704/moscow-time-app
  tag: "v1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30081

resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 5

deployment:
  enabled: false

rollout:
  enabled: true
  strategy: canary
