replicaCount: 2

image:
  repository: enot0704/moscow-time-app
  tag: "v1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30080

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 5

secrets:
  username: "no-commit"
  password: "no-commit"

environment: "dev"
logLevel: "info"

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""

vault:
  enabled: false

deployment:
  enabled: true

rollout:
  enabled: false
  strategy: canary
