apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moscow-time.fullname" . }}-secret
  labels:
    {{- include "moscow-time.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.username | quote }}
  password: {{ .Values.secrets.password | quote }}
